### ISSUE TITLE
Memory leak when adding and removing elements

### ISSUE THREAD

**Issue by ChemicalXandco** [MoonZoon/MoonZoon#157] opened 2023-01-23 22:47 UTC
I have the following:

```rs
use zoon::*;

fn root() -> impl Element {
    let element = RawSvgEl::new("svg");

    let dom_element = element.dom_element();
    Task::start(async move {
        let svg_element = RawSvgEl::new("circle");
        loop {
            dom_element
                .append_child(&svg_element.dom_element())
                .unwrap();
            dom_element
                .remove_child(&svg_element.dom_element())
                .unwrap();
        }
    });

    Row::new().s(Align::center()).item(element)
}

fn main() {
    start_app("app", root);
}
```

When ran on the latest version of firefox, it will quickly run out of RAM. Is there something I am missing? My understanding is that `append_child` and `remove_child` should correctly handle the memory but this does not seem to be happening.

**Comment by databasedav** [comment] 2023-01-25 10:00
`.append_child` and `.remove_child` are from [`web_sys`](https://github.com/rustwasm/wasm-bindgen/tree/main/crates/web-sys) not Zoon so this actually might be an issue on their end, also this isn't the Zoonic way to add and remove children, try doing the test with a signal instead, the Zoonic way e.g.
```rust

use zoon::*;

fn root() -> impl Element {
    let show = Mutable::new(false);
    let element = RawSvgEl::new("svg").child_signal(show.signal().map_true(|| RawSvgEl::new("circle")));

    let dom_element = element.dom_element();
    let wait = 100;
    Task::start(async move {
        loop {
            show.set(!show.get());
            Timer::sleep(wait).await;
        }
    });

    Row::new().s(Align::center()).item(element)
}

fn main() {
    start_app("app", root);
}
```

**Comment by MartinKavik** [comment] 2023-01-30 22:48
I've just tested @ChemicalXandco's example on my machine with Kubuntu:
- Firefox - memory leak
- Chrome - no leak, a dialog box like "the page is unresponsive, kill it?" 
   - The loop is executed on the main thread so it blocks the GUI => it means unresponsiveness is expected behavior in this case.

My super wild guess is Firefox's garbage collector doesn't work properly when the thread is blocked but I didn't try to actually debug the problem. 
So I think the problem isn't directly related to MZ and I don't think I'll be able to resolve it somehow and such `loop` on the main thread blocks everything so it's anti-pattern. Closing the issue, feel free to add more comments when you find more info about the problem in the future or when the problem is fixed thanks to a Firefox update.

**Closed by MartinKavik** 2023-01-30 22:48 UTC
