### ISSUE TITLE
Please add a profiling option to mzoon

### ISSUE THREAD

**Issue by NeverGivinUp** [MoonZoon/MoonZoon#66] opened 2022-02-17 14:53 UTC
Optimizations are usually worse in wasm than in native code. For my computation heavy parts, I need to be able to see the bottlenecks when running in the browser.

Webpack offers a --profiling option, which builds the wasm in release mode but with debug information. Currently there is no way to tell mzoon to use that. Please consider adding that option.

**Comment by MartinKavik** [comment] 2022-02-18 16:18
See the PR https://github.com/MoonZoon/MoonZoon/pull/68
The most important changes:
- https://github.com/MoonZoon/MoonZoon/pull/68/files#diff-fcd58d37a11b715f5b0fa53066717b11d944a9fb8334f7adaa6624ed18c1ded0  (wasm_pack.rs)
- https://github.com/MoonZoon/MoonZoon/pull/68/files#diff-16573b82c7a7db26fdb850abd7a282ad7decd17d9f53657a7ede00757e72111e (build_backend.rs)

I'm not sure if wasm-pack + wasm-opt really don't strip the debug info and if I shouldn't create an extra profile for profiling for the backend app part (instead of just adding a rustflag to a release build).

@NeverGivinUp  Please test it and let me know if it works/what would you like to change before I merge the PR, thank you!

**Comment by NeverGivinUp** [comment] 2022-02-21 15:28
Thanks for the feature, Martin. Allways amazing how fast you add stuff :)

I'm having trouble to get the app running after the update. 

I called 'cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --branch feat/profiling  --root cargo_install_root --locked' to create a mzoon.exe for the branch and moved it to the main directory of the app.
I added the `cors` section to `MoonZoon.toml` and deleted the `cargo.lock` file. 

The backend and frontend work fine with cargo check. However, when trying to start the app I get 

```
cmd.exe /c C:/Users/Navid/Softwareentwicklung/rust_projects/layered_dag_layout_web/mzoon.exe start -r
Start { release: true, profiling: false, open: false }
Building frontend...
Installing wasm-pack...
Failed to get frontend build status
wasm-pack installed
Building backend...
```

What does it mean? And what can I do?

**Comment by MartinKavik** [comment] 2022-02-21 16:33
Could you run the `counter` example when you clone the MoonZoon repo (branch `feat/profiling`)?:
1. cd `examples`
2. cd `counter`
3. `makers mzoon start --profiling --open`  (see https://github.com/MoonZoon/MoonZoon/blob/feat/profiling/docs/development.md)

I thought it's practically  impossible to trigger `Failed to get frontend build status` in https://github.com/MoonZoon/MoonZoon/blob/feat/profiling/crates/mzoon/src/wasm_pack.rs#L83. I'm not sure if your problem is related to `cmd.exe` or `wasm-pack` updating/installing or somehow to new changes in the code. It will need more investigation and probably improve error message handling because the default one isn't clearly expressive enough to help with debugging.

**Comment by NeverGivinUp** [comment] 2022-02-21 16:53
Running it results in this:
```
MoonZoon\examples\counter> makers mzoon start --profiling --open
[cargo-make] INFO - makers 0.35.5
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: mzoon
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: default::legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "run" "--manifest-path" "../../crates/mzoon/Cargo.toml" "start" "--profiling" "--open"
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `C:\Users\Navid\Softwareentwicklung\rust_projects\MoonZoon\target\debug\mzoon.exe start --profiling --open`
Start { release: false, profiling: true, open: true }
Building frontend...
Installing wasm-pack...
wasm-pack installed
Failed to get frontend build status
Building backend...
    Finished release [optimized] target(s) in 0.21s
Backend built
Run backend
Open http://localhost:8080 in the default web browser
Moon config: Config { port: 8080, https: false, compressed_pkg: true, cache_busting: true, backend_log_level: Warn, redirect: Redirect { port: 8081, enabled: false }, cors: Cors { origins: {"*"} } }
Server is running on http://0.0.0.0:8080 [http://localhost:8080]
Cannot load 'frontend/pkg/frontend_bg_0.wasm.gz'. Consider to set `ENV COMPRESSED_PKG false` or build with `mzoon build -r`.
NOT_FOUND: /_api/pkg/frontend_bg_0.wasm
Cannot load 'frontend/pkg/frontend_0.js.gz'. Consider to set `ENV COMPRESSED_PKG false` or build with `mzoon build -r`.
NOT_FOUND: /_api/pkg/frontend_0.js
```

It must be using the right mzoon.exe, because it seems to be fine with the profiling parameter

**Comment by MartinKavik** [comment] 2022-02-21 17:00
I hope the problem isn't caused by something like too long paths on Windows... I have dual-boot Windows & Kubuntu, I'll try to test it on Win at night or tomorrow.

**Comment by MartinKavik** [comment] 2022-02-22 12:30
@NeverGivinUp Please pull the latest changes in the same branch and try it again.

The problem was a bug in the `wasm-pack` version  `0.10.2` on Windows (https://github.com/rustwasm/wasm-pack/issues/1097).

I've downgraded `wasm-pack` to `0.10.1` and also improved error formatting, so the same error will log as:
> Failed to get frontend build status: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the
software publisher. (os error 216)

**Comment by NeverGivinUp** [comment] 2022-02-23 06:09
Thanks @MartinKavik. I can run my app again. However I do not get function names in the profiling output, just wasm-function[###], where ### is some number.

Also when repeatedly stopping and running the app without changing any code, it does a full recompile, as if I had called `cargo clean`. This takes forever!

**Comment by MartinKavik** [comment] 2022-02-23 12:39
I didn't have too much time to testing the changes but I saw similar problems - that's why I haven't merge the PR immediately as I usually do.

---

So I think we should resolve the recompilation problem on the backend side as the first step. Currently, I've just reused `release` profile and enabled the debug info (I hope) by defining RUSTFLAGS to avoid modifying all Cargo.tomls by hand. The code:
```rust
// crates/mzoon/src/build_backend.rs:24

        BuildMode::Profiling => {
            args.push("--release");
            // https://doc.rust-lang.org/rustc/command-line-arguments.html#-g-include-debug-information
            envs.push(("RUSTFLAGS", "-g"));
        }
```
I'm not sure why it triggers recompilation but I would guess it's somehow related to the `envs`. Also the solution isn't very good if you want to switch between `release` and `profiling` mode often because the code has to be always recompiled because both modes share the same directory in the `target` folder.
So I think the better solution would be to introduce a new Cargo.toml profile `profiling` (see [custom profiles](https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles)) and enable the debug info - see https://nnethercote.github.io/perf-book/profiling.html#debug-info (I'm not sure if we want to set the `debuginfo-level = 1` switch mentioned in the link).
Then we would need to update Cargo.toml in all examples and project templates (at least the [demo repository](https://github.com/MoonZoon/demo)).

---

I'm afraid the frontend side would be bit more difficult to fix. The problem:
> However I do not get function names in the profiling output, just wasm-function[###], where ### is some number.

is probably caused by the missing code that should enable the debug info: https://github.com/rustwasm/wasm-pack/blob/4ae6306570a0011246c39c8028a4f11a4236f54b/src/build/mod.rs#L97
But even if we enable the debug info by uncommenting the line of code mentioned above (through a PR to `wasm-pack` or somehow through the MZ code) I'm not sure we won't fall into the trap of recompilation as in the case with the backend side.
Then there should be also a switch for `wasm-opt` in the `wasm-pack` code to disable function names mangling - see the issue for a workaround: https://github.com/rustwasm/wasm-pack/issues/797
Also I'm not sure if `wasm-pack` supports custom profiles (I think Rust wasn't supporting it while the `wasm-pack` has been written) - see, for instance, this issue: https://github.com/rustwasm/wasm-pack/issues/1111. It means we probably won't be able to use the same "trick" and introduce a custom profile `profiling` as we've done for the backend side.
The related code in the PR:
```rust
// crates/mzoon/src/wasm_pack.rs:70

    // https://rustwasm.github.io/docs/wasm-pack/commands/build.html#profile
    match build_mode {
        BuildMode::Dev => args.push("--dev"),
        // @TODO does it work? See
        // https://github.com/rustwasm/wasm-pack/blob/4ae6306570a0011246c39c8028a4f11a4236f54b/src/build/mod.rs#L92-L99
        // and https://github.com/rustwasm/wasm-pack/issues/797
        BuildMode::Profiling => args.push("--profiling"),
        BuildMode::Release => (),
```
When we find out there is no reasonable solution, then we can perform a more invasive surgical cut and remove `wasm-pack` from MoonZoon altogether because there are also other problems with `wasm-pack`, for example:
- The latest version (`0.10.2`) is broken on Windows (explained in the previous comments).
- We can't use `main.rs` + `main` function because of `wasm-pack` limitations.
- It does many things we don't need - e,g. it supports multiple bundlers and Node.js.
 
Note: [Trunk](https://github.com/thedodd/trunk) doesn't use `wasm-pack`, it uses `wasm-bindgen` and `wasm-opt` directly.

---

As you can see, the problem is more complex than it seems at first glance. Unfortunately I won't have time to actively work on this problem following days so feel free to create a new branch from this one and try to find a usable solution. Also I would like to invite you to the [MZ Discord](https://discord.gg/eGduTxK2Es) (if you haven't joined already).

**Comment by MartinKavik** [comment] 2022-02-23 12:44
> This takes forever!
Yes, recompilation is a bug (possible solutions described in the previous comment).
But there were also some regressions in the Rust compiler causing macros-heavy libraries like Actix too slow to compile and also I encountered one compiler Rust bug a few times while writing MZ apps recently. All of them should be fixed and I hope the fixes will be released in the next stable Rust versions - until then you can try to use Rust nightly when you see similar problems.

**Comment by NeverGivinUp** [comment] 2022-02-23 13:44
Unfortunately I have no experience with the backend what so ever. I want to push as much computation to the clients as possible. I will need to use the backend eventually, but so far I'm not using it except as a file server. This also means, that for me, there is currently no profiling need on the backend. The need for profiling on the backend is smaller anyway, as most of the code runs natively compiled for the specific machine -- not in a WASM environment, that has very little knowledge of the machine and its capabilities. Assuming well modularized user code, its performance bottlenecks on the backend can be very well tested in synthetic benchmarks outside of the backend.

As for the frontend: using `wasm-opt = ['-O4', '-g']` in my app's `cargo.toml` (as seen in [the issue you mentioned](https://github.com/rustwasm/wasm-pack/issues/797#issuecomment-619573355)) did produce the function names! Although this technically is a workaround, not a solution I consider this solved for myself. Especially as it also works in release builds.

**Comment by MartinKavik** [comment] 2022-02-23 13:50
[Reopening to not forget to resolve all issues mentioned in the thread]

**Closed** 2022-06-04 14:34 UTC
